name: VRChat Sync

on:
  schedule:
    - cron: '0 * * * *' # каждый час
  workflow_dispatch:

concurrency:
  group: vrchat-sync
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install axios otplib@13.4.1

      - name: Sync VRChat data
        env:
          VRCHAT_USERNAME: ${{ secrets.VRCHAT_USERNAME }}
          VRCHAT_PASSWORD: ${{ secrets.VRCHAT_PASSWORD }}
          VRCHAT_TOTP_SECRET: ${{ secrets.VRCHAT_TOTP_SECRET }}
        run: node .github/scripts/sync.js

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/vrchat.json

          # Если изменений нет — завершаем работу
          git diff --staged --quiet && exit 0

          git commit -m "chore: update vrchat data"

          # Подтягиваем изменения, если кто-то уже успел запушить
          git pull --rebase origin main

          # Публикуем изменения
          git push origin HEAD:main